plugins { id 'com.android.application' }

android {
    namespace 'com.lucas.rollinghorizon'
    compileSdk 35
    buildToolsVersion '35.0.0'

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.lucas.rollinghorizon'
        minSdk 21
        targetSdk 35
        versionCode 637
        versionName '6.37'
    }
}
